//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutorial_boostrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.subvisions = new HashSet<subvision>();
        }
    
        public int id_department { get; set; }
        public string department_name { get; set; }
        public string cheif_department { get; set; }
        public string phone_department { get; set; }
        public string note_department { get; set; }
    
        public virtual ICollection<subvision> subvisions { get; set; }
    }
}
