//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutorial_boostrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subvision
    {
        public int id_subvision { get; set; }
        public string subvision_name { get; set; }
        public string cheif_subvision { get; set; }
        public string phone_subvision { get; set; }
        public string note_subvision { get; set; }
        public string department_name { get; set; }
    
        public virtual department department { get; set; }
    }
}
